#!/usr/bin/env php
<?php

use Moly\Server\MessiServer;

require 'vendor/autoload.php';

$app = require_once 'echo.php';


array_shift( $argv );

$port = empty($argv) ? 80 : array_shift( $argv );


$server = new MessiServer($app, '192.168.2.53', $port);

$server->messiRouter($app->resolve("Moly\Core\Route\Router", true));

$server->listen(function($request, $response) {  
    return $response;
});

