#!/usr/bin/env php
<?php


$server  = stream_socket_server("127.0.0.1:8000", $errno, $errstr);

  while ($socket = stream_socket_accept($server )) {
   
    $client = stream_socket_recvfrom($socket, 4084);

    var_dump($client);


    stream_socket_shutdown($socket, STREAM_SHUT_WR);
  
    fclose($socket);

    
    
  
   
  }

  


?>